# Generated by Django 2.0.3 on 2018-03-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(default=None, null=True)),
                ('route', models.CharField(default='', max_length=128)),
                ('city', models.CharField(default='', max_length=128)),
                ('county', models.CharField(default='', max_length=128)),
                ('state', models.CharField(default='', max_length=128)),
                ('raw_name', models.CharField(default='', max_length=128)),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('link', models.CharField(default='', max_length=128)),
                ('sbl', models.CharField(default='', max_length=128)),
                ('swis', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
